// ============================================================
// BOOKSTORE – MOCK DATABASE
// books-data.js  |  Shared by all pages via <script src="books-data.js">
// Must be loaded BEFORE components.js and main.js
//
// Categories are normalized to exactly match the sidebar filter
// labels in category.html:
//   "Văn học" | "Kinh doanh" | "Thiếu nhi" | "Tâm lý học"
//   "Lịch sử" | "Khoa học"   | "Ngoại ngữ" | "Kỹ năng sống"
// ============================================================

const booksData = [
  {
    id: 'b001',
    name: 'Tử huyệt cảm xúc',
    author: 'Roy Garn',
    price: 68000,
    originalPrice: 95000,
    discount: 28,
    category: 'Kỹ năng sống',
    badge: 'hot',
    sold: 1200,
    rating: 4.8,
    publisher: 'Nhà xuất bản Trẻ',
    year: 2023,
    pages: 320,
    size: '16 × 24 cm',
    cover: 'Bìa mềm',
    language: 'Tiếng Việt',
    image: 'images/Tử huyệt cảm xúc.jpg',
    description: '<b>Tử huyệt cảm xúc</b> là một tác phẩm về tâm lý học và phát triển cá nhân, được viết bởi Roy Garn.',
  },
  {
    id: 'b002',
    name: 'Một đứa con đã khôn ngoan',
    author: 'Nguyễn Công Hoan',
    price: 75000,
    originalPrice: 105000,
    discount: 29,
    category: 'Văn học',
    badge: null,
    sold: 980,
    rating: 4.7,
    publisher: 'Nhà xuất bản Văn học',
    year: 2022,
    pages: 280,
    size: '14 × 20 cm',
    cover: 'Bìa mềm',
    language: 'Tiếng Việt',
    image: 'images/Một đứa con đã khôn ngoan.jpg',
    description: '<b>Một đứa con đã khôn ngoan</b> là một tác phẩm văn học Việt Nam nổi tiếng của nhà văn Nguyễn Công Hoan. Cuốn sách kể về cuộc sống của một đứa trẻ nghèo khó nhưng thông minh và kiên cường, vượt qua nhiều thử thách để đạt được thành công trong cuộc sống. Tác phẩm này không chỉ là một câu chuyện cảm động về sự nỗ lực và kiên trì, mà còn là một bức tranh sinh động về xã hội Việt Nam thời kỳ đó.',
  },
  {
    id: 'b003',
    name: 'Con hoang',
    author: 'Lê Hồng Nguyên',
    price: 89000,
    originalPrice: 120000,
    discount: 26,
    category: 'Văn học',  
    badge: 'new',
    sold: 756,
    rating: 4.6,
    publisher: 'Nhà xuất bản Hội Nhà văn',
    year: 2023,
    pages: 350,
    size: '15 × 23 cm',
    cover: 'Bìa cứng',
    language: 'Tiếng Việt',
    image: 'images/Con hoang.jpg',
    description: '<b>Con hoang</b> là một tác phẩm văn học Việt Nam của nhà văn Lê Hồng Nguyên. Cuốn sách kể về cuộc sống của một đứa trẻ bị bỏ rơi và lớn lên trong hoàn cảnh khó khăn, phải đối mặt với nhiều thử thách và khó khăn để tìm kiếm tình yêu và sự chấp nhận. Tác phẩm này không chỉ là một câu chuyện cảm động về sự kiên cường và lòng nhân ái, mà còn là một bức tranh sinh động về xã hội Việt Nam hiện đại.',
  },
  {
    id: 'b004',
    name: 'Thần, Người Và Đất Việt',
    author: 'Tạ Chí Đại Trường',
    price: 145000,
    originalPrice: 199000,
    discount: 27,
    category: 'Lịch sử',
    badge: 'hot',
    sold: 2100,
    rating: 4.9,
    publisher: 'Nhà xuất bản Tri Thức',
    year: 2021,
    pages: 450,
    size: '16 × 24 cm',
    cover: 'Bìa mềm',
    language: 'Tiếng Việt',
    image: 'images/Thần, Người Và Đất Việt.jpg',
    description: '<b>Thần, Người Và Đất Việt</b> là một tác phẩm lịch sử nổi tiếng của tác giả Tạ Chí Đại Trường. Cuốn sách khám phá những câu chuyện lịch sử đầy cảm hứng và những con người đã đóng góp quan trọng cho đất nước.',
  },
  {
    id: 'b005',
    name: 'Bí Mật Hành Trình Tình Yêu',
    author: 'Roy Garn',
    price: 115000,
    originalPrice: 160000,
    discount: 28,
    category: 'Kỹ năng sống',
    badge: null,
    sold: 1800,
    rating: 4.7,
    publisher: 'Nhà xuất bản Thế Giới',
    year: 2022,
    pages: 290,
    size: '15 × 22 cm',
    cover: 'Bìa mềm',
    language: 'Tiếng Việt',
    image: 'images/Bí Mật Hành Trình Tình Yêu.jpg',
    description: '<b>Bí Mật Hành Trình Tình Yêu</b> là một tác phẩm về tình yêu và sự phát triển cá nhân, được viết bởi Roy Garn.',
  },
  {
    id: 'b006',
    name: 'Tuổi thơ dữ dội',
    author: 'Phùng Quán',
    price: 98000,
    originalPrice: 130000,
    discount: 25,
    category: 'Văn học',   
    badge: null,
    sold: 645,
    rating: 4.5,
    publisher: 'Nhà xuất bản Kim Đồng',
    year: 2020,
    pages: 220,
    size: '14 × 20 cm',
    cover: 'Bìa mềm',
    language: 'Tiếng Việt',
    image: 'images/Tuổi thơ dữ dội.jpg',
    description: '<b>Tuổi thơ dữ dội</b> là một tác phẩm văn học Việt Nam của nhà văn Phùng Quán. Cuốn sách kể về cuộc sống của một đứa trẻ trong thời kỳ chiến tranh, phải đối mặt với nhiều khó khăn và thử thách để trưởng thành.',
  },
  {
    id: 'b007',
    name: 'Năng Đoạn Kim Cương',
    author: 'Michael Roach',
    price: 125000,
    originalPrice: 175000,
    discount: 29,
    category: 'Tâm lý học',
    badge: 'new',
    sold: 430,
    rating: 4.6,
    publisher: 'Nhà xuất bản Lao Động',
    year: 2023,
    pages: 380,
    size: '16 × 24 cm',
    cover: 'Bìa cứng',
    language: 'Tiếng Việt',
    image: 'images/Năng Đoạn Kim Cương.jpg',
    description: '<b>Năng Đoạn Kim Cương</b> là một tác phẩm về tâm lý học và phát triển cá nhân, được viết bởi Michael Roach.',
  },
  {
    id: 'b008',
    name: 'Tuyển Tập Truyện Ngắn Vũ Trọng Phụng',
    author: 'Vũ Trọng Phụng',
    price: 79000,
    originalPrice: 110000,
    discount: 28,
    category: 'Văn học',
    badge: null,
    sold: 870,
    rating: 4.4,
    publisher: 'Nhà xuất bản Văn học',
    year: 2019,
    pages: 250,
    size: '14 × 20 cm',
    cover: 'Bìa mềm',
    language: 'Tiếng Việt',
    image: 'images/Tuyển Tập Truyện Ngắn Vũ Trọng Phụng.jpg',
    description: '<b>Tuyển Tập Truyện Ngắn Vũ Trọng Phụng</b> là một tập hợp các truyện ngắn nổi tiếng của nhà văn Vũ Trọng Phụng.',
  },
  {
    id: 'b009',
    name: 'Nghệ thuật bán hàng bậc cao',
    author: 'Zig Ziglar',
    price: 135000,
    originalPrice: 180000,
    discount: 25,
    category: 'Kinh doanh',
    badge: null,
    sold: 520,
    rating: 4.8,
    publisher: 'Nhà xuất bản Tổng hợp TP.HCM',
    year: 2021,
    pages: 320,
    size: '15 × 23 cm',
    cover: 'Bìa mềm',
    language: 'Tiếng Việt',
    image: 'images/Nghệ thuật bán hàng bậc cao.jpg',
    description: '<b>Nghệ thuật bán hàng bậc cao</b> là một tác phẩm về kỹ năng bán hàng và phát triển bản thân, được viết bởi Zig Ziglar.',
  },
  {
    id: 'b010',
    name: 'Thám Tử Lừng Danh Conan bản đẹp Gosho Aoyama',
    author: 'Gosho Aoyama',
    price: 45000,
    originalPrice: 65000,
    discount: 31,
    category: 'Thiếu nhi',
    badge: 'hot',
    sold: 3200,
    rating: 4.9,
    publisher: 'Nhà xuất bản Kim Đồng',
    year: 2024,
    pages: 180,
    size: '18 × 25 cm',
    cover: 'Bìa mềm',
    language: 'Tiếng Việt',
    image: 'images/Conan.jpg',
    description: '<b>Thám Tử Lừng Danh Conan bản đẹp Gosho Aoyama</b> là một tác phẩm truyện tranh nổi tiếng của tác giả Gosho Aoyama, kể về những vụ án ly kỳ và những cuộc phiêu lưu của thám tử Conan.',
  },
];